"""Initial migration

Revision ID: 001
Revises: 
Create Date: 2026-03-11 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 建立 etf_master 表
    op.create_table(
        'etf_master',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('symbol', sa.String(length=20), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('name_zh', sa.String(length=200), nullable=True),
        sa.Column('issuer', sa.String(length=100), nullable=False),
        sa.Column('asset_class', sa.String(length=50), nullable=False),
        sa.Column('asset_subclass', sa.String(length=50), nullable=True),
        sa.Column('factor_type', sa.String(length=50), nullable=True),
        sa.Column('region', sa.String(length=50), nullable=True),
        sa.Column('sector', sa.String(length=100), nullable=True),
        sa.Column('expense_ratio', sa.Numeric(precision=6, scale=5), nullable=False),
        sa.Column('inception_date', sa.Date(), nullable=False),
        sa.Column('exchange', sa.String(length=20), nullable=False),
        sa.Column('currency', sa.String(length=3), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('is_recommended', sa.Boolean(), nullable=True),
        sa.Column('data_source', sa.String(length=50), nullable=True),
        sa.Column('min_data_year', sa.Integer(), nullable=True),
        sa.Column('liquidity_score', sa.Integer(), nullable=True),
        sa.Column('risk_level', sa.Integer(), nullable=True),
        sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('tracking_index_name', sa.String(length=200), nullable=True),
        sa.Column('tracking_index_symbol', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('last_verified_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('symbol')
    )
    op.create_index(op.f('ix_etf_master_asset_class'), 'etf_master', ['asset_class'], unique=False)
    op.create_index(op.f('ix_etf_master_is_active'), 'etf_master', ['is_active'], unique=False)
    op.create_index(op.f('ix_etf_master_region'), 'etf_master', ['region'], unique=False)
    op.create_index(op.f('ix_etf_master_symbol'), 'etf_master', ['symbol'], unique=False)
    op.create_index('ix_etf_master_tags', 'etf_master', ['tags'], unique=False, postgresql_using='gin')
    
    # 建立 etf_prices 表
    op.create_table(
        'etf_prices',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('symbol', sa.String(length=20), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('open_price', sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column('high_price', sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column('low_price', sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column('close_price', sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column('adjusted_close', sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column('volume', sa.Integer(), nullable=True),
        sa.Column('dividend', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('data_source', sa.String(length=50), nullable=True),
        sa.Column('is_verified', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etf_prices_date'), 'etf_prices', ['date'], unique=False)
    op.create_index(op.f('ix_etf_prices_symbol'), 'etf_prices', ['symbol'], unique=False)
    op.create_index('ix_etf_prices_symbol_date_unique', 'etf_prices', ['symbol', 'date'], unique=True)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_etf_prices_symbol_date_unique', table_name='etf_prices')
    op.drop_index(op.f('ix_etf_prices_symbol'), table_name='etf_prices')
    op.drop_index(op.f('ix_etf_prices_date'), table_name='etf_prices')
    op.drop_table('etf_prices')
    
    op.drop_index('ix_etf_master_tags', table_name='etf_master')
    op.drop_index(op.f('ix_etf_master_symbol'), table_name='etf_master')
    op.drop_index(op.f('ix_etf_master_region'), table_name='etf_master')
    op.drop_index(op.f('ix_etf_master_is_active'), table_name='etf_master')
    op.drop_index(op.f('ix_etf_master_asset_class'), table_name='etf_master')
    op.drop_table('etf_master')
    # ### end Alembic commands ###
